set_property PACKAGE_PIN C8 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN F1 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN G1 [get_ports {light_sensor[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_sensor[0]}]
set_property PACKAGE_PIN G2 [get_ports {light_sensor[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_sensor[1]}]
set_property PACKAGE_PIN G3 [get_ports {light_sensor[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_sensor[2]}]
set_property PACKAGE_PIN G4 [get_ports {light_sensor[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_sensor[3]}]
set_property PACKAGE_PIN G5 [get_ports {light_sensor[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_sensor[4]}]
set_property PACKAGE_PIN G6 [get_ports {light_sensor[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_sensor[5]}]
set_property PACKAGE_PIN G7 [get_ports {light_sensor[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_sensor[6]}]
set_property PACKAGE_PIN G8 [get_ports {light_sensor[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_sensor[7]}]

set_property PACKAGE_PIN H1 [get_ports {obstacle_sensor[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {obstacle_sensor[0]}]
set_property PACKAGE_PIN H2 [get_ports {obstacle_sensor[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {obstacle_sensor[1]}]
set_property PACKAGE_PIN H3 [get_ports {obstacle_sensor[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {obstacle_sensor[2]}]
set_property PACKAGE_PIN H4 [get_ports {obstacle_sensor[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {obstacle_sensor[3]}]
set_property PACKAGE_PIN H5 [get_ports {obstacle_sensor[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {obstacle_sensor[4]}]
set_property PACKAGE_PIN H6 [get_ports {obstacle_sensor[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {obstacle_sensor[5]}]
set_property PACKAGE_PIN H7 [get_ports {obstacle_sensor[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {obstacle_sensor[6]}]
set_property PACKAGE_PIN H8 [get_ports {obstacle_sensor[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {obstacle_sensor[7]}]

set_property PACKAGE_PIN J1 [get_ports {motor_control[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {motor_control[0]}]
set_property PACKAGE_PIN J2 [get_ports {motor_control[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {motor_control[1]}]
